version: "3.9"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3003:3003"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - redis
  postgres:
    image: postgres:latest
    container_name: val_generated
    environment:
      POSTGRES_DB: val_generated
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123455
    ports:
    - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
    - '6379:6379'
    volumes:
      - redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis
    ports:
      - '8081:8081'

volumes:
  postgres-data:
  redis-data: