version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: val_generated
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123455
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: JWT_SECRET
      ACCESS_TOKEN_SECRET: ACCESS_SECRET
      REFRESH_TOKEN_SECRET: REFRESH_SECRET
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: val_generated
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123455
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: