version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    container_name: val_generated
    environment:
      POSTGRES_DB: val_generated
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123455
    ports:
    - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: