version: "3.9"
services:
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
  redis-commander:
    container_name: generated-cache
    hostname: ali
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"